# Generated by Django 3.2.15 on 2022-09-20 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 12 digits allowed.", regex='^998[0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('photo', models.ImageField(blank=True, default='images/male_img.png', null=True, upload_to='profile_images/%d/%m/%Y')),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('host', models.BooleanField(default=False, help_text='The flag to identify whether the user can host a quiz.')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
