# Generated by Django 3.2.15 on 2022-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
