# Generated by Django 3.2.15 on 2022-09-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20220914_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
