# Generated by Django 3.2.15 on 2022-09-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='modified_date',
            new_name='updated_at',
        ),
    ]
