# Generated by Django 3.2.15 on 2022-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220920_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/male_img.png', null=True, upload_to='profile_images/'),
        ),
    ]
