# Generated by Django 3.2.13 on 2022-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_single',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
