# Generated by Django 3.2.15 on 2022-09-15 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_single_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('featured_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='quiz.question')),
            ],
        ),
    ]
