# Generated by Django 3.2.15 on 2022-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20220920_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='host_id',
            field=models.PositiveBigIntegerField(default=6625663742),
        ),
    ]
