# Generated by Django 3.2.15 on 2022-09-19 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=200)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_selected', to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='user_question_answers',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_question_answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_question_answers',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='user_question', to='quiz.question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer_selection',
        ),
        migrations.AddField(
            model_name='answer_choice',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='quiz.user_question_answers'),
        ),
    ]
