# Generated by Django 3.2.15 on 2022-09-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220919_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_choice',
            new_name='AnswerChoice',
        ),
        migrations.RenameModel(
            old_name='Answer_single',
            new_name='AnswerSingle',
        ),
    ]
