# Generated by Django 3.2.15 on 2022-09-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_host_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmeta',
            name='key',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='host_id',
            field=models.PositiveBigIntegerField(default=5935653207, unique=True),
        ),
    ]
