# Generated by Django 3.2.15 on 2022-09-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220923_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='host_id',
            field=models.PositiveBigIntegerField(default=8011903080, unique=True),
        ),
    ]
