# Generated by Django 3.2.15 on 2022-09-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20220923_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_questions', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='host_id',
            field=models.PositiveBigIntegerField(default=6477835838, unique=True),
        ),
    ]
