# Generated by Django 3.2.15 on 2022-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20220924_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='host_id',
            field=models.PositiveBigIntegerField(default=1540712062, unique=True),
        ),
    ]
