# Generated by Django 3.2.15 on 2022-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_quiz_host_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='host_id',
            field=models.IntegerField(default=9947277592, unique=True),
        ),
    ]
