# Generated by Django 3.2.15 on 2022-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, help_text='The brief introduction of the Host User to be displayed on the Test or Quiz Page', max_length=300),
        ),
    ]
